version: "3"
services:
    redis:
        image: "redis:alpine"
        container_name: "${APP_NAME}_redis"
        restart: unless-stopped
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - "${DATA_PATH_HOST}/redis:/data"
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

    fpm:
        build:
            context: ./docker
            dockerfile: Dockerfile.fpm
        container_name: "${APP_NAME}_php_fpm"
        restart: unless-stopped
        logging:
            options:
                max-size: "5k"
        volumes:
            - .:/var/www/html
            - ./docker/php-fpm/laravel.ini:/usr/local/etc/php/conf.d/app.ini
            - ./docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
        networks:
            - sail
        expose:
            - "9000"
        depends_on:
            - mysql
            - redis

    nginx:
        image: nginx:1.27.0-alpine-slim
        container_name: "${APP_NAME}_nginx"
        restart: unless-stopped
        depends_on:
            - fpm
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
        environment:
            - TZ=${APP_TIMEZONE}
        networks:
            - sail

    mysql:
        container_name: "${APP_NAME}_MYSQL"
        image: mysql:8.0.30-debian
        command: --default-authentication-plugin=mysql_native_password
            --max_connections=666
            --bind-address=0.0.0.0
            --transaction-isolation=READ-COMMITTED
        restart: unless-stopped
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - sail-mysql:/var/lib/mysql
            - "./create-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
        cap_add:
            - SYS_NICE # CAP_SYS_NICE
        security_opt:
            - seccomp:unconfined
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

    phpmyadmin:
        container_name: "${APP_NAME}_PHPMYADMIN"
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - 8082:80
        environment:
            PMA_HOSTS: mysql
            PMA_PORT: ${FORWARD_DB_PORT:-3306}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-userpass}
            PMA_ARBITRARY: 1
            UPLOAD_LIMIT: 350M
        networks:
            - sail

networks:
    sail:
        driver: bridge

volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
